package KieRule;
import com.javatechie.spring.drools.api.Order;
//================================================================ Start ============================
rule "HDFC"

when orderObject : Order(cardType=="HDFC" && price>10000);
then orderObject.setDiscount(10);
end;

//================================================================ End ==============================

//================================================================ Start ============================
rule "HDFC_1"

when orderObject : Order(cardType=="HDFC" && price>11000);
then orderObject.setDiscount(orderObject.getDiscount()+5);
end;

//================================================================ End ==============================

//================================================================ Start ============================
rule "ICICI"

when orderObject : Order(cardType=="ICICI" && price<15000);
then orderObject.setDiscount(8);
end;

//================================================================ End ==============================

//================================================================ Start ============================
rule "DBS"

when orderObject : Order(cardType=="DBS" && price>15000);
then orderObject.setDiscount(15);
end;
//================================================================ End ==============================
